Add services.ini, and update README
dod-ccpo/atat-stack pull request #1
Opened 2018-06-04 18:39 UTC by briandds

This PR adds a `services.ini` which has a list of the services managed by this repo. It also updates the README with a bit more information.

2018-06-04 19:55 UTC, jordangov requested changes

2018-06-04 19:55 UTC, jordangov commented on script/test
> +cd services
This won't work if the directory doesn't exist yet, right? We need to either create the directory, or not git ignore it.

2018-06-04 19:55 UTC, jordangov commented on script/test
> +cd services
This won't work if the directory doesn't exist yet, right? We need to either create the directory, or not git ignore it.

2018-06-04 19:56 UTC, jordangov commented on script/test
> +cd services
Ah... I see it's in the other script... hard to tell, maybe a comment here?

2018-06-06 14:25 UTC, briandds commented on script/test
> +cd services
How about this: 5003167?

2018-06-06 16:14 UTC, jordangov commented on script/test
> +cd services
Aaah... yeah, that'll work.

2018-06-06 16:15 UTC, jordangov approved these changes

2018-06-06 16:35 UTC, merged