Foreman
dod-ccpo/atat-stack pull request #3
Opened 2018-06-14 20:51 UTC by dandds

This adds foreman for managing all the services. It's a necessary step along the way to end-to-end testing. It's contingent on [this PR](https://github.com/dod-ccpo/authnid/pull/12) over in authnid. 

If you want to try it before the authnid PR is merged:

- run `script/setup`
- remove the `-d` flag from line 8 of `services/authnid/script/up`

Note that, for now, `script/test` runs all the individual service test suites. On a subsequent PR it will be responsible for running real integration tests.

2018-06-15 13:07 UTC, briandds requested changes

2018-06-15 13:07 UTC, briandds commented on script/server
> +done
It seems like maybe this should happen in `bootstrap` or `setup`

2018-06-15 13:34 UTC, dandds commented
New commits address Brian's suggestion and add a quick script for reaping rogue services. (Sometimes if something goes wrong with foreman, it doesn't seem to kill all the child processes.)

2018-06-15 13:42 UTC, dandds commented
Reverting the reap script until we figure out something better.

2018-06-19 14:27 UTC, briandds approved these changes
Looks good!

2018-06-19 16:01 UTC, merged