End to end tests
dod-ccpo/atat-stack pull request #4
Opened 2018-06-18 19:51 UTC by dandds

This adds a single end-to-end test for user login. It also updates several of the scripts-to-rule-them-all, including `test` and `update`.

2018-06-18 20:03 UTC, dandds commented
Oh, this depends on [this one](https://github.com/dod-ccpo/atat-stack/pull/3). We'll need to merge that first.

2018-06-19 14:31 UTC, briandds requested changes

2018-06-19 14:31 UTC, briandds commented on test/test_up.py
> +
Should `http://localhost:8000` be replaced with `qualified_url('/home')`?

2018-06-19 16:07 UTC, dandds commented
@briandds yup, fixed.

2018-06-19 16:45 UTC, briandds approved these changes

2018-06-19 16:47 UTC, merged